export default {
    "gameName": "Save the Animal",
    "scoreLabel": "Score :",
    "nextAnimalText":"Next Animal",
    "speedLabelText":"Speed : ",
    "gameEndText": "Game Over !!!",
    "gameWidth":1478,
    "gameHeight":831,
    "halfScale":0.5,
    "lobbyBgScale":0.77,
    "lobbyNameY":248,
    "lobbyPlayY":400,
    "playAreaWidth":1000,
    "playAreaHeight":831,
    "animalRotation":90,
    "animalMove":10,
    "speed":1,
    "maxSpeed":4,
    "dashBoardX":1000,
    "dbNameX":1015,
    "dbNameY":30,
    "scoreLabelY":150,
    "scoreHolder":{
        "x":1200,
        "y":135,
        "w":265,
        "h":100
    },
    "scoreHolderColor": 0x000077,
    "scoreValY":15,
    "nextImgX":1100,
    "nextImgY":250,
    "speedLabelY":600,
    "speedVal":{
        "x":1225,
        "y":600
    },
    "buttonPlusX":1300,
    "buttonPlusY":580,
    "buttonMinusY":640,
    "buttonScale":0.8,
    "scoreMultiplier":10,
    "nxtAnimalX":1200,
    "nxtAnimalY":350,
    "animal_names": ['deer', 'chicken', 'crocodile', 'elephant', 'fox', 'girafe', 'panda'],
    "minVelocity":25,
    "fallingAnimal":{
        "x":500,
        "y":1
    }
}
